AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  PureGraalVMAppEagerInit:
    Type: AWS::Serverless::Function
    Properties:
      Handler: does.not.matter
      Runtime: provided
      CodeUri: target/function.zip
      MemorySize: 256
      Timeout: 10
      Tracing: Active

Outputs:
  PureGraalVMAppEagerInitName:
    Description: The name of our PureGraalVMAppEagerInit function
    Value: !Ref PureGraalVMAppEagerInit
