AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MicronautApp:
    Type: AWS::Serverless::Function
    Properties:
      Handler: does.not.matter
      Runtime: provided
      CodeUri: build/function.zip
      MemorySize: 256
      Timeout: 10
      Tracing: Active

Outputs:
  MicronautAppName:
    Description: The name of our MicronautApp function
    Value: !Ref MicronautApp
